version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: main

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 5718
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
